name: inicio 
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.5.1
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
flutter:
  assets:
    - assets/logo.png  
    - assets/images/supermercado1.png
    - assets/images/supermercado2.png
    - assets/images/supermercado3.png
    - assets/images/supermercado4.png
    - assets/images/supermercado5.png
    - assets/images/supermercado6.png
    - assets/images/supermercado7.png
    - assets/images/supermercado8.png
    - assets/images/supermercado9.png
    - assets/images/supermercado10.png
  uses-material-design: true

 
