name: mi_super_tienda
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  assets:
    - assets/logo.png
    - assets/fondoweb.jpg  
    - assets/images/supermercado1.png
    - assets/images/supermercado2.png
    - assets/images/supermercado3.png
    - assets/images/supermercado4.png
    - assets/images/supermercado5.png
    - assets/images/supermercado6.png
    - assets/images/supermercado7.png
    - assets/images/supermercado8.png
    - assets/images/supermercado9.png
    - assets/images/supermercado10.png
    - assets/images/supermercado11.png
    - assets/images/supermercado12.png

    - assets/categorias/tecnologia.png
    - assets/categorias/deportes.jpg
    - assets/categorias/moda.jpg
    - assets/categorias/hogar.jpg
    - assets/categorias/alimentos.jpg
    - assets/categorias/juguetes.jpg

    - assets/productos/iphone16.jpg
    - assets/productos/mac.jpg
    - assets/productos/audifonos.jpg


  uses-material-design: true



 